version: "3"
services:
  wireguard:
    image: linuxserver/wireguard:arm32v7-latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - SERVERURL=pivpndocker.asuscomm.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=5 #optional
      - PEERDNS=auto #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /sharedfolders/Config/Wireguard/config/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped


docker create \
  --name=wireguard \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  -e PUID=1000 \
  -e PGID=100 \
  -e TZ=Europe/London \
  -e SERVERURL=wireguardvpn.asuscomm.com \
  -e SERVERPORT=51820 \
  -e PEERS=5 \
  -e PEERDNS=1.1.1.1 \
  -e INTERNAL_SUBNET=10.13.13.0 `#optional` \
  -p 51820:51820/udp \
  -v /srv/dev-disk-by-label-Siala/Siala/docker/wireguard/config:/config \
  -v /lib/modules:/lib/modules \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  linuxserver/wireguard:arm32v7-latest


sudo docker exec -it wireguard /app/add-peer

sudo docker exec -it wireguard /app/show-peer 1

sudo docker restart wireguard






docker create \
  --name vpn \
  --cap-add=NET_ADMIN \
  --device /dev/net/tun \
  -p 9117:9117 \
  -p 51820:51820 \
  -e NETWORK=192.168.1.0/24 \
  -e USER=qywW7m5iQvbCu2gQkKdD99VH \
  -e PASS='UuHiZqVGGg51JRSDKCTokx7N' \
  bubuntux/nordvpn

docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE --device /dev/net/tun --name vpn \
            --sysctl net.ipv4.conf.all.rp_filter=2 \
            -e USER=user@email.com -e PASS='pas$word' \
            -e CONNECT=country -e TECHNOLOGY=NordLynx -d bubuntux/nordvpn


docker create \
  --name=jackett \
  --restart unless-stopped \
  -e PUID=1000 \
  -e PGID=100 \
  -e TZ=Europe/London \
  --net=container:vpn \
  -v /sharedfolders/Config/Jackett:/config \
  -v /srv/dev-disk-by-label-Siala/Siala:/downloads \
  linuxserver/jackett




enxb827eb75082b

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enxb827eb75082b -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o enxb827eb75082b -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enxb827eb75082b -j MASQUERADE; ip6tables -D FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -D POSTROUTING -o enxb827eb75082b -j MASQUERADE